/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-comm
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoxLineInfo: typeof import('./src/components/comm/boxLineInfo.vue')['default']
    CardInfo1: typeof import('./src/components/codeBox/cardInfo1.vue')['default']
    CodeBox: typeof import('./src/components/codeBox/codeBox.vue')['default']
    CodeBox1: typeof import('./src/components/codeBox/codeBox1.vue')['default']
    CommHeader: typeof import('./src/components/comm/commHeader.vue')['default']
    CommPageBox: typeof import('./src/components/comm/commPageBox.vue')['default']
    ElAnchor: typeof import('element-plus/es')['ElAnchor']
    ElAnchorLink: typeof import('element-plus/es')['ElAnchorLink']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    LeftComm: typeof import('./src/components/comm/leftComm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
